# Generated by Django 5.0.7 on 2024-09-18 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bookstorea', '0004_clientes_compras_empleados_roles_usuarios_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compras',
            name='num_factura',
            field=models.IntegerField(),
        ),
    ]
