# Generated by Django 5.0.7 on 2024-09-25 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bookstorea', '0005_alter_compras_num_factura'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lotes',
            name='precio_venta',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
